// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package link_cut_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkCutClient is the client API for LinkCut service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkCutClient interface {
	// Sends a greeting
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type linkCutClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkCutClient(cc grpc.ClientConnInterface) LinkCutClient {
	return &linkCutClient{cc}
}

func (c *linkCutClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/link_cut_api.LinkCut/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkCutClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/link_cut_api.LinkCut/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkCutServer is the server API for LinkCut service.
// All implementations must embed UnimplementedLinkCutServer
// for forward compatibility
type LinkCutServer interface {
	// Sends a greeting
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	mustEmbedUnimplementedLinkCutServer()
}

// UnimplementedLinkCutServer must be embedded to have forward compatible implementations.
type UnimplementedLinkCutServer struct {
}

func (UnimplementedLinkCutServer) Create(context.Context, *CreateRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLinkCutServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLinkCutServer) mustEmbedUnimplementedLinkCutServer() {}

// UnsafeLinkCutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkCutServer will
// result in compilation errors.
type UnsafeLinkCutServer interface {
	mustEmbedUnimplementedLinkCutServer()
}

func RegisterLinkCutServer(s grpc.ServiceRegistrar, srv LinkCutServer) {
	s.RegisterService(&LinkCut_ServiceDesc, srv)
}

func _LinkCut_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkCutServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link_cut_api.LinkCut/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkCutServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkCut_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkCutServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link_cut_api.LinkCut/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkCutServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkCut_ServiceDesc is the grpc.ServiceDesc for LinkCut service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkCut_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "link_cut_api.LinkCut",
	HandlerType: (*LinkCutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LinkCut_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LinkCut_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link-cut-api.proto",
}
